export const ExtraOptionTable = {
  Temporal_M_Str: 1,
  Temporal_M_Agi: 1,
  Temporal_M_Vit: 1,
  Temporal_M_Int: 1,
  Temporal_M_Dex: 1,
  Temporal_M_Luk: 1,

  Temporal_Armor_TW: 2,
  Temporal_Cape_TW: 1,

  Imperial_Breath_Armor: 1,
  Imperial_Knight_Armor: 1,
  Imperial_Spear_Armor: 1,
  Imperial_Genesis_Armor: 1,
  Imperial_Sharp_Suit: 1,
  Imperial_Aim_Suit: 1,
  Imperial_Severe_Suit: 1,
  Imperial_Reverb_Suit: 1,
  Imperial_Adora_Robe: 1,
  Imperial_Duple_Robe: 1,
  Imperial_Knuckle_Suit: 1,
  Imperial_Tiger_Suit: 1,
  Imperial_Tonado_Armor: 1,
  Imperial_Vulcan_Armor: 1,
  Imperial_Kart_Suit: 1,
  Imperial_Kart_Suit2: 1,
  Imperial_Rolling_Suit: 1,
  Imperial_Assasin_Suit: 1,
  Imperial_Fatal_Suit: 1,
  Imperial_Stalker_Suit: 1,
  Imperial_Picky_Robe: 1,
  Imperial_Carrot_Robe: 1,
  Imperial_Trip_Suit: 1,
  Imperial_Firerain_Suit: 1,
  Imperial_Crimson_Robe: 1,
  Imperial_Frost_Robe: 1,
  Imperial_Psychic_Robe: 1,
  Imperial_Dust_Robe: 1,
  Imperial_Sun_Suit: 1,
  Imperial_Moon_Suit: 1,
  Imperial_Ninja_Suit: 1,
  Imperial_Kunai_Suit: 1,
  Imperial_Swhoo_Robe: 1,
  Imperial_Explosion_Robe: 1,
  Imperial_Snovice_Suit: 1,
  Imperial_Snovice_Robe: 1,
  Imperial_Attack_Manteau: 1,
  Imperial_Magic_Manteau: 1,

  Grace_Breath_Armor: 1,
  Grace_Knight_Armor: 1,
  Grace_Spear_Armor: 1,
  Grace_Genesis_Armor: 1,
  Grace_Sharp_Suit: 1,
  Grace_Aim_Suit: 1,
  Grace_Severe_Suit: 1,
  Grace_Reverb_Suit: 1,
  Grace_Adora_Robe: 1,
  Grace_Duple_Robe: 1,
  Grace_Knuckle_Suit: 1,
  Grace_Tiger_Suit: 1,
  Grace_Tonado_Armor: 1,
  Grace_Vulcan_Armor: 1,
  Grace_Kart_Suit: 1,
  Grace_Kart_Suit2: 1,
  Grace_Rolling_Suit: 1,
  Grace_Assasin_Suit: 1,
  Grace_Fatal_Suit: 1,
  Grace_Stalker_Suit: 1,
  Grace_Picky_Robe: 1,
  Grace_Carrot_Robe: 1,
  Grace_Trip_Suit: 1,
  Grace_Firerain_Suit: 1,
  Grace_Crimson_Robe: 1,
  Grace_Frost_Robe: 1,
  Grace_Psychic_Robe: 1,
  Grace_Dust_Robe: 1,
  Grace_Sun_Suit: 1,
  Grace_Moon_Suit: 1,
  Grace_Ninja_Suit: 1,
  Grace_Kunai_Suit: 1,
  Grace_Swhoo_Robe: 1,
  Grace_Explosion_Robe: 1,
  Grace_Snovice_Suit: 1,
  Grace_Snovice_Robe: 1,
  Grace_Attack_Manteau: 2,
  Grace_Magic_Manteau: 2,

  Overwhelm_Str_Armor: 2,
  Overwhelm_Int_Armor: 2,
  Overwhelm_Luk_Armor: 2,
  Overwhelm_Vit_Armor: 2,
  Overwhelm_Agi_Armor: 2,
  Overwhelm_Dex_Armor: 2,

  //Temporal_Armor_TW_LT: 2,

  DragonA_Red: 3,
  DragonA_Green: 3,
  DragonA_Gold: 3,
  DragonA_Purple: 3,
  DragonA_Blue: 3,
  DragonA_Silver: 3,

  Victory_Wing_Ear_: 2,
  Deepblue_Sunglasses_: 2,
  Battle_Processor_: 2,

  Bag_Of_Antonio_Melee: 2,
  Bag_Of_Antonio_Range: 2,
  Bag_Of_Antonio_Magic: 2,

  Thanatos_Pendant: 2,
  Red_Force_Pendant: 2,
  Blue_Mental_Pendant: 2,

  Geffen_Mage_Robe: 2,
  Anti_Magic_Suit: 2,
  Ring_Of_Spell_Explosion: 2,
  Body_Power_Up_Ring: 2,

  Bloody_Knight_Shield_: 2,
  Bloody_Knight_Shield__: 3,
  Gambler_Seal: 2,
  Droop_Gunslinger: 2,
  Cat_Lace_Hairband_K: 2,
  Kafra_Suit: 1,
  SeeOtter_Fan: 2,
  FurSeal_Fan: 2,
  SeeOtter_Fan_LT: 2,
  FurSeal_Fan_LT: 2,

  Ear_Of_Flame_TH: 2,
  Ear_Of_Soul_TH: 2,
  Ear_Of_Abyss_TH: 3,
 
  Gambler_Seal_KR_: 3,

  MD_Geffen_Shield: 3,
  MD_Geffen_Shield2: 3,
  //Spade_Ace_Melee: 2,
} as const;
