import { int, luk, str, vit } from "./_basic"

export const dimensionHead4 = [
  ...str(1, 5),
  ...int(1, 5),
  ...vit(1, 5),
  ...luk(1, 5),
]
export const dimensionHead3 = [
  "T_D_Jewel_STR_1",
  "T_D_Jewel_STR_2",
  "T_D_Jewel_STR_3",
  "T_D_Jewel_AGI_1",
  "T_D_Jewel_AGI_2",
  "T_D_Jewel_AGI_3",
  "T_D_Jewel_DEX_1",
  "T_D_Jewel_DEX_2",
  "T_D_Jewel_DEX_3",
  "T_D_Jewel_VIT_1",
  "T_D_Jewel_VIT_2",
  "T_D_Jewel_VIT_3",
  "T_D_Jewel_INT_1",
  "T_D_Jewel_INT_2",
  "T_D_Jewel_INT_3",
  "T_D_Jewel_LUK_1",
  "T_D_Jewel_LUK_2",
  "T_D_Jewel_LUK_3",
  "T_D_Jewel_SPR_1",
  "T_D_Jewel_SPR_2",
  "T_D_Jewel_SPR_3",
  "T_D_Jewel_WIS_1",
  "T_D_Jewel_WIS_2",
  "T_D_Jewel_WIS_3",
  "T_D_Jewel_POW_1",
  "T_D_Jewel_POW_2",
  "T_D_Jewel_POW_3",
  "T_D_Jewel_CON_1",
  "T_D_Jewel_CON_2",
  "T_D_Jewel_CON_3",
]
export const dimensionHead2 = [
  'Acute_Jewel_3',
  'Acute_Jewel_4',
  'Acute_Jewel_5',
  'Acute_Jewel_6',
  'Acute_Jewel_7',
  'Acute_Jewel_8',
  'Acute_Jewel_9',
  'Acute_Jewel_10',
  'Tenacity_Jewel_3',
  'Tenacity_Jewel_4',
  'Tenacity_Jewel_5',
  'Tenacity_Jewel_6',
  'Tenacity_Jewel_7',
  'Tenacity_Jewel_8',
  'Tenacity_Jewel_9',
  'Tenacity_Jewel_10',
  'Master_A_Jewel_3',
  'Master_A_Jewel_4',
  'Master_A_Jewel_5',
  'Master_A_Jewel_6',
  'Master_A_Jewel_7',
  'Master_A_Jewel_8',
  'Master_A_Jewel_9',
  'Master_A_Jewel_10',
  'Mettle_Jewel_3',
  'Mettle_Jewel_4',
  'Mettle_Jewel_5',
  'Mettle_Jewel_6',
  'Mettle_Jewel_7',
  'Mettle_Jewel_8',
  'Mettle_Jewel_9',
  'Mettle_Jewel_10',
  'Magic_E_Jewel_3',
  'Magic_E_Jewel_4',
  'Magic_E_Jewel_5',
  'Magic_E_Jewel_6',
  'Magic_E_Jewel_7',
  'Magic_E_Jewel_8',
  'Magic_E_Jewel_9',
  'Magic_E_Jewel_10',
  'Spell_Jewel_3',
  'Spell_Jewel_4',
  'Spell_Jewel_5',
  'Spell_Jewel_6',
  'Spell_Jewel_7',
  'Spell_Jewel_8',
  'Spell_Jewel_9',
  'Spell_Jewel_10',
  'Adamatine_Jewel_3',
  'Adamatine_Jewel_4',
  'Adamatine_Jewel_5',
  'Adamatine_Jewel_6',
  'Adamatine_Jewel_7',
  'Adamatine_Jewel_8',
  'Adamatine_Jewel_9',
  'Adamatine_Jewel_10',
  'Fierce_A_Jewel_3',
  'Fierce_A_Jewel_4',
  'Fierce_A_Jewel_5',
  'Fierce_A_Jewel_6',
  'Fierce_A_Jewel_7',
  'Fierce_A_Jewel_8',
  'Fierce_A_Jewel_9',
  'Fierce_A_Jewel_10',
  'Great_C_Jewel_3',
  'Great_C_Jewel_4',
  'Great_C_Jewel_5',
  'Great_C_Jewel_6',
  'Great_C_Jewel_7',
  'Great_C_Jewel_8',
  'Great_C_Jewel_8',
  'Great_C_Jewel_9',
  'Great_C_Jewel_10',
]

export const dimensionWeapon3 = [
  "Barmund_Flame3",
  "Barmund_Ice3",
  "Barmund_Plain3",
  "Barmund_Death3",
  'Barmund_Poison3',
]
export const dimensionWeapon4 = [
  "Bio_Jam_Df2",
  "Bio_Jam_Es2",
  "Bio_Jam_Vl2",
  "Bio_Jam_Eq2",
  "Bio_Jam_Hd2",
]

export const dimensionAcc4 = [
  //   'Pow_Orb_1',
  // 'Pow_Orb_2',
  // 'Pow_Orb_3',
  // 'Pow_Orb_4',
  // 'Pow_Orb_5',
  'Pow_Orb_6',
  'Pow_Orb_7',
  'Pow_Orb_8',
  'Pow_Orb_9',
  'Pow_Orb_10',
  'Pow_Orb_11',
  'Pow_Orb_12',
  'Pow_Orb_13',
  'Pow_Orb_14',
  'Pow_Orb_15',
  'Pow_Orb_16',
  'Pow_Orb_17',
  'Pow_Orb_18',
  'Pow_Orb_19',
  'Pow_Orb_20',
  // 'Spl_Orb_1',
  // 'Spl_Orb_2',
  // 'Spl_Orb_3',
  // 'Spl_Orb_4',
  // 'Spl_Orb_5',
  'Spl_Orb_6',
  'Spl_Orb_7',
  'Spl_Orb_8',
  'Spl_Orb_9',
  'Spl_Orb_10',
  'Spl_Orb_11',
  'Spl_Orb_12',
  'Spl_Orb_13',
  'Spl_Orb_14',
  'Spl_Orb_15',
  'Spl_Orb_16',
  'Spl_Orb_17',
  'Spl_Orb_18',
  'Spl_Orb_19',
  'Spl_Orb_20',
]
export const dimensionAcc3 = [
  // 'Warrior_Orb_1',
  // 'Warrior_Orb_2',
  // 'Warrior_Orb_3',
  // 'Warrior_Orb_4',
  // 'Warrior_Orb_5',
  'Warrior_Orb_6',
  'Warrior_Orb_7',
  'Warrior_Orb_8',
  'Warrior_Orb_9',
  'Warrior_Orb_10',
  'Warrior_Orb_11',
  'Warrior_Orb_12',
  'Warrior_Orb_13',
  'Warrior_Orb_14',
  'Warrior_Orb_15',
  // 'Shooter_Orb_1',
  // 'Shooter_Orb_2',
  // 'Shooter_Orb_3',
  // 'Shooter_Orb_4',
  // 'Shooter_Orb_5',
  'Shooter_Orb_6',
  'Shooter_Orb_7',
  'Shooter_Orb_8',
  'Shooter_Orb_9',
  'Shooter_Orb_10',
  'Shooter_Orb_11',
  'Shooter_Orb_12',
  'Shooter_Orb_13',
  'Shooter_Orb_14',
  'Shooter_Orb_15',
  // 'Magician_Orb_1',
  // 'Magician_Orb_2',
  // 'Magician_Orb_3',
  // 'Magician_Orb_4',
  // 'Magician_Orb_5',
  'Magician_Orb_6',
  'Magician_Orb_7',
  'Magician_Orb_8',
  'Magician_Orb_9',
  'Magician_Orb_10',
  'Magician_Orb_11',
  'Magician_Orb_12',
  'Magician_Orb_13',
  'Magician_Orb_14',
  'Magician_Orb_15',
]

export const timeGap4 = [
  'Bio_Jam_Df2',
  'Bio_Jam_Es2',
  'Bio_Jam_Vl2',
  'Bio_Jam_Eq2',
  'Bio_Jam_Hd2',
]

export const timeGap3 = [
  'Barmund_Flame3',
  'Barmund_Ice3',
  'Barmund_Plain3',
  'Barmund_Death3',
  'Barmund_Poison3',
]