import { reDimGlacierArmor2, reDimGlacierArmor3, reDimGlacierArmor4 } from './re_dim_glacier';

/**
 * These three lists are generated by numeric range, so an off-by-one silently
 * points a slot at an aegis name that does not exist in item.json (the enchant
 * just never shows up in the dropdown). Guard the boundaries.
 */
describe('Re-Dim Glacier enchant lists', () => {
  it('slot 2 is Star Cluster Lv1-3 for the six trait stats', () => {
    expect(reDimGlacierArmor2.length).toBe(18);
    expect(reDimGlacierArmor2).toContain('Star_Cluster_Of_Pow1');
    expect(reDimGlacierArmor2).toContain('Star_Cluster_Of_Wis3');
    expect(reDimGlacierArmor2).not.toContain('Star_Cluster_Of_Pow4');
  });

  it('slot 3 covers only the skill spells, skipping the stat orbs 150-161', () => {
    expect(reDimGlacierArmor3.length).toBe(179);
    expect(reDimGlacierArmor3).toContain('Glacier_F_Orb_1');
    expect(reDimGlacierArmor3).toContain('Glacier_F_Orb_149');
    expect(reDimGlacierArmor3).toContain('Glacier_F_Orb_162');
    expect(reDimGlacierArmor3).toContain('Glacier_F_Orb_191');
    expect(reDimGlacierArmor3).not.toContain('Glacier_F_Orb_150');
    expect(reDimGlacierArmor3).not.toContain('Glacier_F_Orb_161');
    expect(reDimGlacierArmor3).not.toContain('Glacier_F_Orb_192');
  });

  it('slot 4 is Star of ... Lv1-5 plus the six trait +3 orbs', () => {
    expect(reDimGlacierArmor4.length).toBe(7 * 5 + 6);
    expect(reDimGlacierArmor4).toContain('Star_Of_MasterArcher1');
    expect(reDimGlacierArmor4).toContain('Star_Of_Spirit5');
    expect(reDimGlacierArmor4).toContain('M_Crt3');
    expect(reDimGlacierArmor4).not.toContain('Star_Of_Spirit6');
  });

  it('has no duplicates in any slot', () => {
    for (const list of [reDimGlacierArmor2, reDimGlacierArmor3, reDimGlacierArmor4]) {
      expect(list.filter((name, i) => list.indexOf(name) !== i)).toEqual([]);
    }
  });
});
